### ISSUE TITLE
Call button

### ISSUE THREAD

**Issue by simwir** [simwir/Shuttle-Train#1]
A GUI button to call the train to a station

**Comment by stanfear** [comment]
what you could do is keep track of all trains and add a button to the interface when a trainstop is open 
then, if a player clicks it, you send the first train available and with a path to the trainstop that the player has oppened

**Comment by simwir** [comment]
Instead of first available maybe the closest. I'm pretty sure i saw some distance calculating functions when browsing the API

**Comment by simwir** [comment]
Closed by #9
