### ISSUE TITLE
same named stations releases multiple shuttles [bug/"its a feature"]

### ISSUE THREAD

**Issue by rwaltr** [simwir/Shuttle-Train#12]
If a shuttle is called to a station that has more than one instance of its name. it will multiply its request by the number of stations with the same name. flooding the network with shuttles. as per normal factorio train logic.

Although I cant imagine how this really would be a problem. Especialy since you can filter your stations and I use "#shutt" to mark shuttle stations with unique names.

Granted This could be used to send all shuttles to "shuttle storage" ;D

**Comment by simwir** [comment]
Fixed by @stanfear in #15
