### ISSUE TITLE
Station filter

### ISSUE THREAD

**Issue by simwir** [simwir/Shuttle-Train#2]
A text field in which you can enter a filter for the stations you want to have displayed in the list

**Comment by DofD10** [comment]
Maybe add the option for different tags fe. #PAX

**Comment by simwir** [comment]
@DofD10 What do you mean by a tag? Would that not just be somthing thats part of the name of the station?

**Comment by stanfear** [comment]
hey, I made a pull request for this issue, fell free to merge it or not :)
(it works quite well how I did it)

**Comment by simwir** [comment]
There is now a stations filter thanks to @stanfear. #6
