### ISSUE TITLE
Set stack size to 5

### ISSUE THREAD

**Issue by joozek78** [simwir/Shuttle-Train#20]
I don't get why stack size is set to 1. Normal locomotives and FARLs stack to 5, so why shouldn't shuttles too? I often run around with a few trains in my pocket to accommodate for unexpected travels and sometimes you forget to grab one as leave.

**Comment by simwir** [comment]
Yes it should, and it is in the next version. I just need to get around to releasing it. If you can't wait read my guide [here](https://simwir.dk/2016/04/want-to-get-the-latest-updates-first/), on how to download it manually.
