### ISSUE TITLE
[Request] Adjust recipe/technology order

### ISSUE THREAD

**Issue by ST-DDT** [simwir/Shuttle-Train#22]
It would be cool if you could adjust the recipe order. The smart train should either be directly before the default train or after it, but not first in the rail section.

See this screenshot for explanation:
![order](https://cloud.githubusercontent.com/assets/1579362/15632804/885645e0-259d-11e6-92eb-b085194444f0.png)

The same applies to the smart train technology.

Use the "order" tag for this. If you need help with that I can help/do it for you.

**Comment by simwir** [comment]
You're right it should be ordered like that, and if you know how the sorting system works you are more than welcome to do it, because i do not know how it works :)

**Comment by ST-DDT** [comment]
Here the PR that fixes this issue: https://github.com/simwir/Shuttle-Train/pull/24

**Comment by ST-DDT** [comment]
I also created [PR #3](https://github.com/Choumiko/RailTanker/pull/3) on [RailTanker](https://github.com/Choumiko/RailTanker) to fix the final ordering, because RailTanker currently uses the wrong order tag and thus would be between the diesel-locomotive and the shuttle-train.
