### ISSUE TITLE
Rotate if no path

### ISSUE THREAD

**Issue by simwir** [simwir/Shuttle-Train#3]
If the train doesn't have a path to the desired station, the train should rotate and try in the opposite direction

**Comment by stanfear** [comment]
Ok, I made a few checks ingame, it seems there is no way to rotate a train through code ...
well, there is a way, using orientation  and adding 0.5 to it but .... then when the train return to moving, the train resets its orientation to what it was

**Comment by simwir** [comment]
Ok. Well i think that 9 times out of 10 it's not going to be a problem anyway, since most train systems is set up to be one way anyway. And for that 1 time when it might be, you will just have to rotate it yourself.

**Comment by stanfear** [comment]
or, you can make the shuttle have two locomotives, one in each direction (make one apear and connect (if it is possible through code) when one is placed) although, this is probably not a really good solution

**Comment by simwir** [comment]
If people have 2 headed setups, they can add to trains together facing away from each other, just like normal. They need to craft 2 trains in vanilla too.

**Comment by stanfear** [comment]
Yeah, well, I think this issue should be closed (and maybe, if a no_path is detected, just warn the player that's in the train)

**Comment by simwir** [comment]
Issue closed, but not fixed
