### ISSUE TITLE
Lingering issues with Dynamic Stops

### ISSUE THREAD

**Issue by kaufman-bryce** [simwir/Shuttle-Train#31]
The following error occurs, under circumstances that I have found hard to pin down. My leading theory is that the issue is related to bad data in an existing save created prior to the initial fix. (I was unable to reproduce the error in a sandbox cheat-mode test save)
http://puu.sh/q74YH/5cf5faf7a2.jpg

Looking through Control.lua, this error shouldn't be possible because when the filtered list is created, it checks to ensure it doesn't add the same stop name twice.
Also creating pull request with minor changes that prevent this error.

**Comment by simwir** [comment]
Fixed in [commit ](https://github.com/simwir/Shuttle-Train/commit/e66f1a96632b1900d8da2836e89d0085ff793bc7)
