### ISSUE TITLE
Factorio .14.4 - No vertical selection shift in entity prototype

### ISSUE THREAD

**Issue by Nexela** [simwir/Shuttle-Train#36]
.14.4 adds vertical_selection_shift, as a mandatory field for trains

Simple fix is to add vertical_selection_shift = -0.5, to the train prototype (this is the default for vanilla)

**Comment by simwir** [comment]
Thanks for notifying me that a new major factorio version had been released.
This bug has been fixed with commit: [58724d6985f59e85b11949d84613a183f2f09cbd](https://github.com/simwir/Shuttle-Train/commit/58724d6985f59e85b11949d84613a183f2f09cbd)
