### ISSUE TITLE
Does not recognize smart train stops as train stops.

### ISSUE THREAD

**Issue by simwir** [simwir/Shuttle-Train#5]
The shuttle does not recognize smart train stops from the [SmartTrains](https://forums.factorio.com/viewtopic.php?f=97&t=14432) mod as train stops.
Possibly only a problem in multiplayer.

**Comment by Roktaal** [comment]
For me it does recognize smart train stop from SmartTrains

**Comment by simwir** [comment]
Ok, it must be the multiplayer part then.

**Comment by DofD10** [comment]
Then i am curious as if i start the MP map in SP mode it still does not recognize them. But might be something with forces going on?!

**Comment by simwir** [comment]
Most likely closed by #9 The problem seemed to lie in indexing old files, so not MP. Any pre-existing smart train stops would not be imported to the list due to using name instead of type in:
`global.trainStations = global.trainStations or game.get_surface(1).find_entities_filtered{area = {{-10000,-10000}, {10000,10000}}, type="train-stop"} or {}`
